### ISSUE TITLE
`Paragraph` doesn't implement `Debug` while `Deb822` does, however, probably incomplete

### ISSUE THREAD

**Issue by michalfita** [jelmer/deb822-rs#206]
In `src/lossless.rs` there's following implementation:
```rust
impl std::fmt::Debug for Deb822 {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Deb822").finish()
    }
}
```
but there's none for `Paragraph` leading to trouble with tests elsewhere.

However, the above seem to be incomplete, as it seems it should be more like:
```rust
impl std::fmt::Debug for Deb822 {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Deb822")
            .field("0", &self.0)
            .finish()
    }
}
```
to actually be useful anywhere for debugging.

I was thinking about moving these into `ast_node!()` macro or switching to `#[derive(Debug)]` for them.

**Comment by jelmer** [comment]
Can you send a PR?
